#networks:
#  prod_network:
#    driver: bridge
#  stage_network:
#    driver: bridge

services:
  nginx:
    image: nginx:1.29.7-alpine
    container_name: api_proxy
    ports:
      - "8000:8000"
    volumes:
      - ./etc/nginx/templates:/etc/nginx/templates
    environment:
      SERVER_NAME: ${SERVER_NAME}
      API_HOST: api
      API_PORT: ${API_PORT}
    depends_on:
      api:
        condition: service_started

  db:
    image: postgres:17-alpine
    container_name: analytics-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  mongo:
    image: mongo:7
    container_name: sync-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.runCommand({ ping: 1 }).ok"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: analytics-api
    restart: unless-stopped
    env_file: 
      - path: "./.env"
    depends_on:
      db:
        condition: service_healthy
      mongo:
        condition: service_healthy
    volumes:
      - ./alembic:/app/alembic
      - ./tests:/app/tests
      - ./app:/app/app
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: db
      POSTGRES_PORT: ${POSTGRES_PORT}
      MONGO_URI: mongodb://mongo:27017
      MONGO_DB: ${MONGO_DB:-opepic_sync}

volumes:
  db_data:
  mongo_data:
