from typing import Protocol

from app.application.authentication.commands import UserLoginCommand, UserRegistrationCommand
from app.application.authentication.responses import ResolvedUserResponse


class AuthenticationProtocol(Protocol):

    def verify_token(self, token: str) -> str: ...
    def resolve_user(self, token: str) -> ResolvedUserResponse: ...
    def login(self, command: UserLoginCommand) -> ResolvedUserResponse: ...
    def register(self, command: UserRegistrationCommand) -> ResolvedUserResponse: ...