from typing import Protocol
from app.application.users.commands import UserRegistrationCommand, UserUpdateCommand
from app.application.users.responses import UserResponse

class UserServiceProtocol(Protocol):
    def register(self, command: UserRegistrationCommand) -> UserResponse: ...
    def update(self, user_id: int, command: UserUpdateCommand) -> UserResponse: ...
    def delete(self, user_id: int) -> None: ...
    def get_by_id(self, user_id: int) -> UserResponse: ...
